// Off-script design-sync generator for Construct (@neuravision/construct).
//
// Construct is a pure CSS/token, framework-agnostic design system: components
// are BEM-style CSS classes on semantic HTML, there is no JS component bundle
// (`window.<Global>.*`). The standard React converter (package-build.mjs) does
// not apply. This generator produces the claude.ai/design upload layout the
// app + package-validate.mjs consume, "by whatever means the repo allows":
//
//   - flatten the repo's authored CSS (foundations + tokens + components) into
//     one _ds_bundle.css, reachable via styles.css's @import closure
//   - a minimal, honest _ds_bundle.js (header + components: []) — no JS API
//   - one preview card per component, built from the TRUE rendered HTML scraped
//     out of the reference Storybook (the fidelity oracle), wrapped in
//     <html data-theme="light"> so it renders themed exactly like Storybook
//   - a .prompt.md per component teaching the real class vocabulary + markup
//
// Run: node .design-sync/build.mjs   (from repo root)

import { createServer } from 'node:http';
import { chromium } from 'playwright';
import {
  existsSync, mkdirSync, readFileSync, writeFileSync, rmSync, readdirSync, statSync,
} from 'node:fs';
import { dirname, resolve, relative, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const SBREF = resolve(REPO, '.design-sync/sb-reference');
const OUT = resolve(REPO, 'ds-bundle');
const NAMESPACE = 'Construct';

const argComponents = (() => {
  const i = process.argv.indexOf('--components');
  return i > 0 ? new Set(process.argv[i + 1].split(',').map((s) => s.trim())) : null;
})();

// ---------------------------------------------------------------------------
// 1. Flatten CSS  (foundations + tokens + all component css → _ds_bundle.css)
// ---------------------------------------------------------------------------
function inlineCss(absPath, seen, remote) {
  if (seen.has(absPath)) return '';
  seen.add(absPath);
  if (!existsSync(absPath)) return `/* missing: ${relative(REPO, absPath)} */\n`;
  const css = readFileSync(absPath, 'utf8');
  return css.replace(
    /@import\s+(?:url\(\s*)?["']([^"']+)["']\s*\)?\s*;?/g,
    (_m, spec) => {
      if (/^(https?:)?\/\//.test(spec) || spec.startsWith('http')) {
        remote.push(`@import url("${spec}");`);
        return '';
      }
      const child = resolve(dirname(absPath), spec);
      return `\n/* ${relative(REPO, child)} */\n` + inlineCss(child, seen, remote);
    },
  );
}

function buildBundleCss() {
  const seen = new Set();
  const remote = [];
  // tokens first so custom props are defined before use; foundations next
  // (base resets/body, drops its dup tokens import + hoists the font import);
  // then every component stylesheet via index.css.
  const tokens = inlineCss(resolve(REPO, 'tokens/tokens.css'), seen, remote);
  const foundations = inlineCss(resolve(REPO, 'foundations.css'), seen, remote);
  const components = inlineCss(resolve(REPO, 'components/index.css'), seen, remote);
  const hoisted = [...new Set(remote)].join('\n');
  return [
    '/* Construct design system — flattened bundle (generated by .design-sync/build.mjs) */',
    hoisted,
    '/* ---- tokens ---- */', tokens,
    '/* ---- foundations ---- */', foundations,
    '/* ---- components ---- */', components,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// 2. Component model from the Storybook index
// ---------------------------------------------------------------------------
function loadComponents() {
  const idx = JSON.parse(readFileSync(join(SBREF, 'index.json'), 'utf8'));
  const byKey = new Map();
  for (const e of Object.values(idx.entries)) {
    if (e.type !== 'story') continue;
    const group = e.title.split('/')[0].trim();
    const display = e.title.split('/').slice(1).join(' / ').trim() || e.title;
    const name = e.importPath.split('/').pop().replace(/\.stories\.\w+$/, '');
    if (argComponents && !argComponents.has(name)) continue;
    if (!byKey.has(e.title)) byKey.set(e.title, { name, display, group, title: e.title, stories: [] });
    byKey.get(e.title).stories.push({ id: e.id, name: e.name, exportName: e.exportName });
  }
  return [...byKey.values()];
}

// Components that present wide (full-width layouts/tables) → stacked one-per-row
// cards instead of a multi-column grid, so they aren't cramped in a cell.
const STACKED = new Set([
  'AppShell', 'AppShellV2', 'Sidebar', 'Navbar', 'DataTable', 'DataTableSimple',
  'CardAndTable', 'Toolbar', 'Drawer', 'Tree', 'List', 'Datepicker', 'Chart', 'Combobox',
  'Banner', // full-width notices — present better one-per-row than in a narrow grid cell
]);

// ---------------------------------------------------------------------------
// 3. Static server for the reference Storybook
// ---------------------------------------------------------------------------
const MIME = {
  '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
  '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.woff': 'font/woff',
  '.woff2': 'font/woff2', '.ttf': 'font/ttf', '.map': 'application/json',
};
function serve(dir) {
  const srv = createServer((req, res) => {
    try {
      let p = decodeURIComponent(req.url.split('?')[0]);
      if (p.endsWith('/')) p += 'index.html';
      const f = join(dir, p);
      if (!existsSync(f) || statSync(f).isDirectory()) { res.writeHead(404); res.end(); return; }
      res.writeHead(200, { 'content-type': MIME[extname(f)] || 'application/octet-stream' });
      res.end(readFileSync(f));
    } catch { res.writeHead(500); res.end(); }
  });
  return new Promise((r) => srv.listen(0, '127.0.0.1', () => r({ srv, port: srv.address().port })));
}

// ---------------------------------------------------------------------------
// 4. Scrape rendered HTML per story
// ---------------------------------------------------------------------------
async function scrape(components) {
  const { srv, port } = await serve(SBREF);
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: 'light' });
  let scraped = 0, failed = 0;
  for (const comp of components) {
    for (const story of comp.stories) {
      const url = `http://127.0.0.1:${port}/iframe.html?id=${encodeURIComponent(story.id)}&viewMode=story`;
      try {
        await page.goto(url, { waitUntil: 'load', timeout: 20000 });
        await page.waitForSelector('#storybook-root', { state: 'attached', timeout: 15000 });
        // settle: wait for content + fonts, then normalise focus so cards and
        // the oracle don't differ on a play-induced focus ring.
        await page.waitForFunction(
          () => document.querySelector('#storybook-root')?.innerHTML.trim().length > 0,
          { timeout: 10000 },
        ).catch(() => {});
        await page.evaluate(() => document.fonts && document.fonts.ready).catch(() => {});
        await page.waitForTimeout(250);
        const html = await page.evaluate(() => {
          if (document.activeElement && document.activeElement !== document.body) {
            try { document.activeElement.blur(); } catch {}
          }
          const root = document.querySelector('#storybook-root');
          return root ? root.innerHTML.trim() : '';
        });
        story.html = html;
        if (html) scraped++; else { failed++; story.empty = true; }
      } catch (e) {
        failed++;
        story.error = String(e).split('\n')[0];
        story.html = '';
      }
    }
  }
  await browser.close();
  srv.close();
  return { scraped, failed };
}

// ---------------------------------------------------------------------------
// 5. Emit layout
// ---------------------------------------------------------------------------
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Classes whose CSS is position:fixed and present the component AS the overlay
// (modal/drawer/toast/fixed-banner). A cell holding one needs vertical room +
// clipping so the contained overlay is visible without bleeding. Layout
// components (app-shell/navbar/sidebar) also use fixed but are tall already —
// universal mount containment handles them without min-height.
const OVERLAY_MARKERS = ['ct-modal', 'ct-drawer', 'ct-toast-region', 'ct-banner--fixed'];
// A fixed element designed to sit OFF-screen until focus (the skip link lives at
// top:-100px). Mount containment makes that offset relative to the cell, which
// would otherwise reveal it; clip the cell so it stays hidden like in Storybook.
const CLIP_MARKERS = ['ct-skip-link'];

function cardHtml(comp) {
  const stacked = STACKED.has(comp.name) || comp.group === 'Layout';
  const cells = comp.stories.map((s, i) => {
    const body = s.html || `<p style="color:var(--color-text-error,#c00)">⚠ story did not render${s.error ? `: ${esc(s.error)}` : ''}</p>`;
    const overlay = !!s.html && OVERLAY_MARKERS.some((m) => s.html.includes(m));
    const clip = !overlay && !!s.html && CLIP_MARKERS.some((m) => s.html.includes(m));
    const cls = overlay ? ' ds-overlay' : clip ? ' ds-clip' : '';
    return `      <section class="ds-cell">\n        <h4>${esc(s.name)}</h4>\n        <div id="r${i}" class="ds-mount${cls}">${body}</div>\n      </section>`;
  }).join('\n');
  const gridCss = stacked
    ? '.ds-grid{display:flex;flex-direction:column;gap:20px}'
    : '.ds-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px;align-items:start}';
  return `<!-- @dsCard group="${comp.group}" -->
<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(comp.display)}</title>
<link rel="stylesheet" href="../../../styles.css">
<style>
  html,body{margin:0}
  body{padding:24px;background:var(--color-bg-canvas);color:var(--color-text-primary);font-family:var(--font-family-text,system-ui)}
  ${gridCss}
  .ds-cell{background:var(--color-bg-surface,#fff);border:1px solid var(--color-border,#e5e7eb);border-radius:var(--radius-lg,10px);padding:16px;min-width:0;overflow:auto}
  .ds-cell>h4{margin:0 0 12px;font:600 11px/1.4 var(--font-family-text,system-ui);color:var(--color-text-secondary,#667);text-transform:uppercase;letter-spacing:.06em}
  /* Each mount is a containing block for position:fixed descendants, so an
     overlay (modal/drawer/toast) is contained to its own cell and cannot
     bleed across the grid. */
  .ds-mount{position:relative;transform:translateZ(0)}
  .ds-mount.ds-overlay{min-height:360px;overflow:hidden}
  .ds-mount.ds-clip{overflow:hidden}
</style>
</head>
<body>
  <div class="ds-grid">
${cells}
  </div>
</body>
</html>
`;
}

function classVocab(comp) {
  const classes = new Set();
  for (const s of comp.stories) {
    if (!s.html) continue;
    for (const m of s.html.matchAll(/class="([^"]+)"/g)) {
      for (const c of m[1].split(/\s+/)) if (c.startsWith('ct-')) classes.add(c);
    }
  }
  return [...classes].sort();
}

function promptMd(comp) {
  const classes = classVocab(comp);
  const primary = comp.stories.find((s) => s.html && s.html.length < 1600) || comp.stories.find((s) => s.html) || comp.stories[0];
  const example = primary?.html ? primary.html : '';
  const lines = [];
  lines.push(`${comp.display} — ${comp.group} component (Construct). Plain CSS classes on semantic HTML; no JS import — load \`styles.css\` and use the classes below.`);
  lines.push('');
  if (classes.length) {
    lines.push('## CSS classes');
    lines.push(classes.map((c) => `\`${c}\``).join(', '));
    lines.push('');
  }
  if (example) {
    lines.push(`## Example markup (${primary.name})`);
    lines.push('```html');
    lines.push(example.length > 2400 ? example.slice(0, 2400) + '\n<!-- … truncated; see the preview card -->' : example);
    lines.push('```');
    lines.push('');
  }
  lines.push('## Variants in this component');
  lines.push(comp.stories.map((s) => `- ${s.name}`).join('\n'));
  lines.push('');
  lines.push('Theme: wrap in an element with `data-theme="light" | "dark" | "high-contrast"` (light is the `:root` default).');
  return lines.join('\n') + '\n';
}

function emit(components, bundleCss) {
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  // root files
  writeFileSync(join(OUT, '_ds_bundle.css'), bundleCss);
  writeFileSync(join(OUT, 'styles.css'),
    '/* Construct — styles entry. Designs receive this @import closure. */\n@import "./_ds_bundle.css";\n');
  writeFileSync(join(OUT, '_ds_bundle.js'),
    `/* @ds-bundle: {"namespace":"${NAMESPACE}","components":[],"sourceHashes":{},"inlinedExternals":[]} */\n` +
    `(function(){window.${NAMESPACE}=window.${NAMESPACE}||{};})();\n`);

  // tokens (reference copies — already inlined into the bundle)
  mkdirSync(join(OUT, 'tokens'), { recursive: true });
  for (const f of ['tokens.css', 'tokens.json']) {
    if (existsSync(resolve(REPO, 'tokens', f))) writeFileSync(join(OUT, 'tokens', f), readFileSync(resolve(REPO, 'tokens', f)));
  }

  // components
  let previews = 0;
  for (const comp of components) {
    const dir = join(OUT, 'components', comp.group, comp.name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, `${comp.name}.html`), cardHtml(comp));
    writeFileSync(join(dir, `${comp.name}.prompt.md`), promptMd(comp));
    previews++;
  }

  // README (prepend conventions header if authored)
  const conv = resolve(REPO, '.design-sync/conventions.md');
  const header = existsSync(conv) ? readFileSync(conv, 'utf8').trimEnd() + '\n\n---\n\n' : '';
  const byGroup = {};
  for (const c of components) (byGroup[c.group] ??= []).push(c);
  const index = Object.keys(byGroup).sort().map((g) =>
    `### ${g}\n\n` + byGroup[g].map((c) => `- **${c.display}** — \`components/${g}/${c.name}/\` (${c.stories.length} variant${c.stories.length === 1 ? '' : 's'})`).join('\n'),
  ).join('\n\n');
  writeFileSync(join(OUT, 'README.md'),
    `${header}# Construct Design System\n\nToken-based, framework-agnostic CSS design system (\`@neuravision/construct\`). ` +
    `Components are BEM-style CSS classes on semantic HTML — load \`styles.css\` and apply the classes. No JS runtime.\n\n` +
    `## Components\n\n${index}\n`);

  // app recompile sentinel — emitted here so a clean rebuild never leaves it
  // missing before an upload push (the OUT dir is wiped each run).
  writeFileSync(join(OUT, '_ds_needs_recompile'), 'recompile\n');

  // local-only build metadata (not uploaded)
  writeFileSync(join(OUT, '.ds-build-meta.json'),
    JSON.stringify({ componentCount: previews, shape: 'storybook', namespace: NAMESPACE, generator: 'off-script-css' }, null, 2));

  return previews;
}

// ---------------------------------------------------------------------------
async function main() {
  if (!existsSync(join(SBREF, 'index.json'))) {
    console.error('✗ sb-reference/index.json missing — build it: npx storybook build -c .storybook -o .design-sync/sb-reference');
    process.exit(1);
  }
  const components = loadComponents();
  console.error(`components: ${components.length}, stories: ${components.reduce((n, c) => n + c.stories.length, 0)}`);
  const bundleCss = buildBundleCss();
  console.error(`_ds_bundle.css: ${(bundleCss.length / 1024).toFixed(0)} KB`);

  // Scrape cache: the rendered HTML only changes when the DS source / stories
  // change (then rebuild sb-reference + pass --rescrape). Template-only edits
  // reuse the cache and skip the browser entirely.
  const CACHE = resolve(REPO, '.design-sync/.cache/scraped.json');
  const force = process.argv.includes('--rescrape');
  let scraped = 0, failed = 0, usedCache = false;
  if (!force && existsSync(CACHE)) {
    const cache = JSON.parse(readFileSync(CACHE, 'utf8'));
    let miss = 0;
    for (const c of components) for (const s of c.stories) {
      if (Object.prototype.hasOwnProperty.call(cache, s.id)) { s.html = cache[s.id]; if (s.html) scraped++; else { failed++; s.empty = true; } } else miss++;
    }
    if (miss === 0) { usedCache = true; console.error(`loaded ${scraped} stories from scrape cache (--rescrape to refresh)`); }
    else console.error(`scrape cache incomplete (${miss} missing) — re-scraping`);
  }
  if (!usedCache) {
    console.error('scraping story HTML from sb-reference …');
    ({ scraped, failed } = await scrape(components));
    const cache = {};
    for (const c of components) for (const s of c.stories) cache[s.id] = s.html ?? '';
    mkdirSync(dirname(CACHE), { recursive: true });
    writeFileSync(CACHE, JSON.stringify(cache));
    console.error(`scraped ${scraped} stories${failed ? `, ${failed} empty/failed` : ''}`);
  }
  const previews = emit(components, bundleCss);
  console.error(`✓ emitted ${previews} component cards → ${relative(REPO, OUT)}`);
  if (failed) {
    const probs = components.flatMap((c) => c.stories.filter((s) => s.empty || s.error).map((s) => `  ${c.name}/${s.name}: ${s.error || 'empty render'}`));
    console.error('stories that did not render:\n' + probs.join('\n'));
  }
}
main().catch((e) => { console.error(e); process.exit(1); });
